### ISSUE TITLE
Crash when upload multiple images concurrently 

### ISSUE THREAD

**Issue by abdifardin** [expo/firebase-storage-upload-example#7]
For about two weeks i was struggling with crashing on expo ios standalone app when i tried to upload multiple image in a same times.

There was no crash report in my testflight dashboard nor from xcode crash window.

Also no js crash report from sentry.

Finally i figured it out by cleaning my codes. First i thought its its memory leaks when i kept uploaded image in states to show preview and i removed the related codes but it was still crashing.
Then i kept those codes and removed firebase api calls for uploading images. Now everything works fine.

So Im sure its an issue with this new api and i just reverted the codes to the old approach by @aaronksaunders  https://github.com/aaronksaunders/expo-rn-firebase-image-upload
With that approach the crash still exist, but the rate reduced from 60% to less than 5% of times.

I hope you guys help to find the reason.

Thanks

**Comment by hounsellal** [comment]
I think I have a similar problem. About 20% of the time, just uploading a single audio file with this method causes the app to restart randomly. No error is called. It just restarts in the middle of an upload. @FakhruddinAbdi : did you end up getting this to work some other way than reverting to the old approach of @aaronksaunders? I'm on SDK 29 currently.

**Comment by abdifardin** [comment]
I found a thread in react-native-firebase package issues which someone said it doesn't crash, it just hangs because the upload process happening on the main thread of the device.

So the only solution i have found is detaching from expo and use `react-native-firebase` to use firebase queries
In their most recent version, they have solved this issue.
